### ISSUE TITLE
[Proj4] Assembly files & Output do not match SimpleC programs

### ISSUE THREAD

**Issue by Quikks1lver** [cop3402fall20/test-cases-public#2]
Hello, Dr. G & TAs:

I hope you guys are having a pleasant break, and I don't like to be the guy to create "issues" during break, but I wanted to let you know of some problems I was having with the proj4 test cases ASAP, as the semester is rapidly drawing to a close.

I will also note that I'm the first to admit my code may have issues, but the problems I bring up should not be affected by that since I traced the test cases by hand.

I tested many of the **proj4** files, and none of the assembly files I tested match what one would expect them to for the corresponding ``.simplec`` file. For example, ``nested.simplec`` has if statements and while loops, which should translate to labels such as ``.L0, .L1, .L2`` in the corresponding ``nested.s`` file, but ``nested.s`` has no such branching or labels. In fact, none of the assembly files have any labels or branching. This branching issue causes some of the return values to be incorrect, since the assembly does not consider changes that happen within the branching.

Additionally, a couple of the test cases (ex: ``factorial.simplec``) have relational operators that are not required for the project 4 scope (these are for bonus).

Lastly, I ran the graders script on these files and my code, and my code was failing ``long.simplec``. This may be an error on my end or the test case issue mentioned above. Note that I did do this test case individually and it compiled and ran OK. In any case, after the graders script failed this, it didn't even run the other cases, which could be an issue as failing one halts everything else and fails to run other cases.

Please reach out with any questions.

**Comment by paulgazz** [comment]
I'm seeing what you are talking about.  @kaisil has fixed the relational operators AFAICT.  The solution compiler produces control-flow with labels for nested.simplec, so @kaisil will look into what happened in generating the test cases.

**Comment by kaisil** [comment]
The issue has been resolved and the corrected test cases uploaded just now so be sure to get a fresh pull. Sorry about the confusion!
